# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: ꟼK
title: Katja Pretnar
logo: "/assets/images/kp1.png"
email: "katjapretnar@mailbox.org"
description: Personal website for sharing climbing adventures and artsy projects.
#twitter_username: username
github_username: katjapretnar
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

google_site_verification: "YC6lIVGAHPRKRvDH4Dztg1B6YxTgNCPx1Qeep5swrBo"

author:
  name   : "ꟼK"
  avatar : "/assets/images/k_out.png"
  bio    : "Yet another climber & engineer."
  location: SLO & AUT
  links:
 #   - label: "Website"
 #     icon: "fas fa-fw fa-link"
 #     url: "https://katjapretnar.github.io"
    - label: "...@mailbox.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:katjapretnar@mailbox.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/katja-pretnar-324391138"
    - label : "About"
      icon: "fa-solid fa-dove"
      url: /about/
  #  - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
  #    url: "https://github.com/katjapretnar"
  #  - label: "CV"
  #    icon: "fas fa-fw fa-file"
  #    url: "https://"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/katjapretnar"
    - label: Posts by Category
      icon: "fa-solid fa-icons"
      url: /categories/
    - label: by Tag
      icon: "fa-solid fa-tags"
      url: /tags/
    - label: by Year
      icon: "fa-solid fa-clock"
      url: /posts/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
